# Generated by Django 3.1.3 on 2020-11-24 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('internship_id', models.IntegerField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=50, verbose_name='Internship Position')),
                ('pay', models.CharField(max_length=7, null=True, verbose_name='Pay')),
                ('organization_name', models.CharField(max_length=255, verbose_name='Organization')),
                ('organization_url', models.CharField(max_length=255, null=True, verbose_name='URL')),
                ('organization_address', models.CharField(max_length=255, verbose_name='Mailing Address')),
                ('supervisor_name', models.CharField(max_length=255, verbose_name='Supervisor Name')),
                ('supervisor_position', models.CharField(max_length=255, null=True, verbose_name='Supervisor Position')),
                ('supervisor_email', models.CharField(max_length=255, null=True, verbose_name='Supervisor Email')),
                ('supervisor_phone', models.CharField(max_length=100, null=True, verbose_name='Supervisor Phone')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('unh_id', models.CharField(max_length=15, unique=True, verbose_name='UNH_id')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last Name')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First Name')),
                ('school_email', models.EmailField(max_length=255, verbose_name='School Email')),
                ('major', models.CharField(max_length=255, verbose_name='Major Name')),
                ('degree', models.CharField(max_length=255, verbose_name='Degree Name')),
                ('linkedin', models.CharField(max_length=255, verbose_name='LinkedIn Profile')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(default='COMP805', max_length=50, null=True, verbose_name='Course ID')),
                ('student_credits', models.CharField(default=3, max_length=10, null=True, verbose_name='student credits')),
                ('semester', models.CharField(max_length=30, verbose_name='Semester')),
                ('year', models.CharField(max_length=10, verbose_name='Year')),
                ('instructor', models.CharField(max_length=40, verbose_name='Instructor')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('internshipid', models.ForeignKey(db_column='internship_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.internship')),
                ('studentid', models.ForeignKey(db_column='student_id', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.student')),
            ],
        ),
    ]
