# Generated by Django 3.1.1 on 2020-11-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='organization_url',
            field=models.CharField(max_length=255, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='pay',
            field=models.CharField(max_length=7, null=True, verbose_name='Pay'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='supervisor_email',
            field=models.CharField(max_length=255, null=True, verbose_name='Supervisor Email'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='supervisor_phone',
            field=models.CharField(max_length=100, null=True, verbose_name='Supervisor Phone'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='supervisor_position',
            field=models.CharField(max_length=255, null=True, verbose_name='Supervisor Position'),
        ),
        migrations.AlterField(
            model_name='internshipassignment',
            name='course_id',
            field=models.CharField(max_length=50, verbose_name='Course ID'),
        ),
        migrations.AlterField(
            model_name='internshipassignment',
            name='credits',
            field=models.CharField(max_length=10, verbose_name='Credits'),
        ),
        migrations.AlterField(
            model_name='internshipassignment',
            name='instructor',
            field=models.CharField(max_length=40, verbose_name='Instructor'),
        ),
        migrations.AlterField(
            model_name='internshipassignment',
            name='semester',
            field=models.CharField(max_length=30, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='internshipassignment',
            name='year',
            field=models.CharField(max_length=10, verbose_name='Year'),
        ),
    ]
