# Generated by Django 3.1.1 on 2020-11-15 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipassignment',
            name='internship_id',
        ),
        migrations.RemoveField(
            model_name='internshipassignment',
            name='student_id',
        ),
        migrations.AddField(
            model_name='internshipassignment',
            name='internshipid',
            field=models.ForeignKey(db_column='internship_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.internship'),
        ),
        migrations.AddField(
            model_name='internshipassignment',
            name='studentid',
            field=models.ForeignKey(db_column='student_id', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.student'),
        ),
        migrations.AlterField(
            model_name='internshipassignment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
