# Generated by Django 3.1.3 on 2021-04-02 22:56

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_auto_20201124_0638'),
    ]

    operations = [
    migrations.CreateModel(
    name = 'roles',
    fields=[
    ('role_name', models.CharField(max_length=255, null=True))
    ]),
    ]
