# Generated by Django 3.1.3 on 2021-04-03 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_auto_20210402_2256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='roles',
        ),
        migrations.AlterField(
            model_name='internship',
            name='internship_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='internship',
            name='organization_address',
            field=models.CharField(max_length=255, null=True, verbose_name='Mailing Address'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='organization_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='pay',
            field=models.CharField(max_length=255, null=True, verbose_name='Pay'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='position',
            field=models.CharField(max_length=255, null=True, verbose_name='Internship Position'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='supervisor_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Supervisor Name'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='supervisor_phone',
            field=models.CharField(max_length=255, null=True, verbose_name='Supervisor Phone'),
        ),
        migrations.AlterField(
            model_name='internshipassignment',
            name='instructor',
            field=models.CharField(max_length=40, null=True, verbose_name='Instructor'),
        ),
        migrations.AlterField(
            model_name='internshipassignment',
            name='semester',
            field=models.CharField(max_length=30, null=True, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='internshipassignment',
            name='studentid',
            field=models.ForeignKey(db_column='student_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.student'),
        ),
        migrations.AlterField(
            model_name='internshipassignment',
            name='year',
            field=models.CharField(max_length=10, null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.CharField(max_length=255, null=True, verbose_name='Degree Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='linkedin',
            field=models.CharField(max_length=255, null=True, verbose_name='LinkedIn Profile'),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(max_length=255, null=True, verbose_name='Major Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_email',
            field=models.EmailField(max_length=255, null=True, verbose_name='School Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
