# Generated by Django 3.1.3 on 2021-04-03 15:23
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models, migrations

def load_default_groups(apps,schema_editor):
    from django.core.management import call_command
    call_command("loaddata","roles")

class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0004_auto_20210403_1418'),
    ]

    operations = [
            migrations.RunPython(load_default_groups),
    ]
