# Generated by Django 3.1.3 on 2021-05-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0006_auto_20210403_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipassignment',
            name='end_date',
            field=models.DateField(null=True, verbose_name='End Date'),
        ),
    ]
