# Generated by Django 3.1.3 on 2021-05-16 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0007_auto_20210516_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipassignment',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='End Date'),
            preserve_default=False,
        ),
    ]
